### PR TITLE
corrections and new pictures

### PR DESCRIPTION
**Pull request by Thezamp**

### CODE REVIEW

**Review by Thezamp — COMMENTED** [review]
ok

**Review by Thezamp — COMMENTED** [review]
ok

**Review by Thezamp — COMMENTED** [review]
Ok

**Comment by HashakGik** [comment]
Hi, can you shortly describe what this pull request changes in the template?

Thank you.

**Comment by Thezamp** [comment]
Hey I'm super sorry, I was using an editor I'm not experienced with and pushed on the wrong repository, please ignore this

**Comment by HashakGik** [comment]
No problem ;)

**Pull request closed without merging**
